name: Build and Release Windows Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone beszel repository
      run: git clone https://github.com/henrygd/beszel.git

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        check-latest: true

    - name: Build binary
      run: |
        cd beszel/beszel/cmd/agent
        export GOOS=windows
        export GOARCH=amd64
        export CGO_ENABLED=0
        go build -ldflags "-w -s" .

    - name: Get latest non-prelease version
      id: get_latest_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/henrygd/beszel/releases | jq -r 'map(select(.prerelease == false)) | .[0].tag_name')
        echo "latest_release=$latest_release" >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ env.latest_release }}
        release_name: Release ${{ env.latest_release }}
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: beszel/beszel/cmd/agent/agent.exe
        asset_name: agent.exe
        asset_content_type: application/octet-stream