name: Build and Release Windows Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone beszel repository
      run: git clone https://github.com/henrygd/beszel.git

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true

    - name: Build binary
      run: |
        cd beszel/beszel/cmd/agent
        export GOOS=windows
        export GOARCH=amd64
        export CGO_ENABLED=0
        go build -ldflags "-w -s" .

    - name: Get latest non-prelease version
      id: get_latest_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/henrygd/beszel/releases | jq -r 'map(select(.prerelease == false)) | .[0].tag_name')
        echo "latest_release=$latest_release" >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v2.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        token: '${{ github.token }}'
        files: 'beszel/beszel/cmd/agent/agent.exe'
        tag_name: ${{ env.latest_release }}
        prerelease: false
        name: Release ${{ env.latest_release }}
        draft: false
        make_latest: true
